### ISSUE TITLE
the trait bound `JiebaTokenizer: Tokenizer` is not satisfied

### ISSUE THREAD

**Issue by ddv404** [jiegec/tantivy-jieba#7]
use tantivy::schema::Schema;
    use tantivy::tokenizer::*;
    use tantivy::Index;
    let tokenizer = tantivy_jieba::JiebaTokenizer {};
        let mut schema_builder = Schema::builder();
        let schema = schema_builder.build();
    let index = Index::create_in_ram(schema);
    index.tokenizers()
        .register("jieba", tokenizer);

the trait bound `JiebaTokenizer: Tokenizer` is not satisfied
the following other types implement trait `Tokenizer`:
  FacetTokenizer
  NgramTokenizer
  RawTokenizer
  SimpleTokenizer
  WhitespaceTokenizer
required for `TextAnalyzer` to implement

**Comment by jiegec** [comment]
Please ensure you are using the same tantivy version as tantivy-jiebas does.

**Comment by jiegec** [comment]
If you are using a newer tantivy verison, I can publish a new version of tantivy-jieba to match it.

**Comment by jiegec** [comment]
I have released new version based on latest tantivy, please retry.

**Comment by eruca** [comment]
确定是tantivy 0.21版本，同样的错误

**Comment by jiegec** [comment]
> 确定是tantivy 0.21版本，同样的错误

Please update to latest tantivy-jieba.
